# NUMPY PRACTICE

In [1]:
import numpy as np

In [2]:
myarr = np.array([[4,5,2,8]], np.int64)

In [3]:
myarr

array([[4, 5, 2, 8]], dtype=int64)

In [4]:
myarr.shape

(1, 4)

# Array Creation: Conversion from other Python structures (i.e. lists and tuples)

In [5]:
arraylist = np.array([[1,5,2,6], [5,7,8,6], [8,9,6,3]])

In [6]:
arraylist

array([[1, 5, 2, 6],
       [5, 7, 8, 6],
       [8, 9, 6, 3]])

In [7]:
 arraylist.dtype

dtype('int32')

In [8]:
arraylist.shape

(3, 4)

In [9]:
arraylist.size

12

In [10]:
arraylist[1,3]= 15

In [11]:
arraylist

array([[ 1,  5,  2,  6],
       [ 5,  7,  8, 15],
       [ 8,  9,  6,  3]])

In [12]:
np.array({1,5,3,8})

array({8, 1, 3, 5}, dtype=object)

# **Intrinsic NumPy array creation functions**

In [13]:
zeros = np.zeros((2,5))

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
zeros.dtype

dtype('float64')

In [16]:
zeros.shape

(2, 5)

In [17]:
rng = np.arange(15)

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace = np.linspace(1,5,10)

In [20]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [21]:
emp = np.empty((1,5))

In [22]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        0.00000000e+000, 0.00000000e+000]])

In [23]:
emplike = np.empty_like(lspace)

In [24]:
emplike

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [25]:
ide = np.identity(45)

In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
ide.shape

(45, 45)

In [28]:
arr = np.arange(99)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr = arr.reshape(3,33)

In [31]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr =arr.ravel()

In [34]:
arr.shape

(99,)

# NUMPY AXIS

In [35]:
x =[[1,2,3],[4,5,6], [7,1,0]]

In [36]:
ar = np.array(x)

In [37]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
ar.sum(axis=0)

array([12,  8,  9])

In [39]:
ar.sum(axis=1)

array([ 6, 15,  8])

**Transpose the original array**

In [40]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [41]:
ar.flat

In [42]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


**chedck the number of dimensions**

In [43]:
ar.ndim

2

In [44]:
ar.size

9

In [45]:
ar.nbytes

36

# # Working with 1D array

In [46]:
one = np.array([1,2,555,66,7,8])

In [47]:
one. argmax()

2

In [48]:
one.argmin()

0

In [49]:
one.argsort()

array([0, 1, 4, 5, 3, 2], dtype=int64)

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar.argmax()

6

In [52]:
ar.argmin()

8

In [53]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [54]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [55]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [56]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [57]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [58]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
ar2=np.array([[1,2,1],
             [4,0,6],
             [8,1,0]])

In [61]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [62]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [63]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar.sum()

29

In [66]:
ar.max()

7

In [67]:
ar.min()

0

**FIND ELEMENT IN ARRAY**

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [70]:
type(np.where(ar>5))

tuple

In [71]:
np.count_nonzero(ar)

8

# HOW NUMPY TAKE LESS SPACE?

In [72]:
import sys

In [73]:
py_ar =[0,4,55,2]

In [74]:
np_ar =np.array(py_ar)

In [75]:
sys.getsizeof(1) * len(py_ar)

112

In [76]:
np_ar.itemsize * np_ar.size

16